// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proyecto_BK.Entities
{
    public partial class tbAlimentos
    {
        public tbAlimentos()
        {
            tbCombosPersonales = new HashSet<tbCombosPersonales>();
            tbFacturaDetalle = new HashSet<tbFacturaDetalle>();
            tbPaquetesPorComidas = new HashSet<tbPaquetesPorComidas>();
            tbPromocionesPorComidas = new HashSet<tbPromocionesPorComidas>();
        }

        public int Alim_Id { get; set; }
        public string Alim_Descripcion { get; set; }
        public decimal? Alim_Precio { get; set; }
        public string Alim_Imagen { get; set; }
        public int? Alim_Usua_Creacion { get; set; }
        public DateTime? Alim_Fecha_Creacion { get; set; }
        public int? Alim_Usua_Modifica { get; set; }
        public DateTime? Alim_Fecha_Modifica { get; set; }
        public bool? Alim_Estado { get; set; }

        public virtual tbUsuarios Alim_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Alim_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbCombosPersonales> tbCombosPersonales { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; }
        public virtual ICollection<tbPaquetesPorComidas> tbPaquetesPorComidas { get; set; }
        public virtual ICollection<tbPromocionesPorComidas> tbPromocionesPorComidas { get; set; }
    }
}