// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Proyecto_BK.Entities;

#nullable disable

namespace Proyecto_BK.DataAccess
{
    public partial class DbsistemarestaurantebkContext : DbContext
    {
        public DbsistemarestaurantebkContext()
        {
        }

        public DbsistemarestaurantebkContext(DbContextOptions<DbsistemarestaurantebkContext> options)
            : base(options)
        {
        }

      
        public virtual DbSet<tbAlimentos> tbAlimentos { get; set; }
        public virtual DbSet<tbBebidas> tbBebidas { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbClientes> tbClientes { get; set; }
        public virtual DbSet<tbCombosPersonales> tbCombosPersonales { get; set; }
        public virtual DbSet<tbComplementos> tbComplementos { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbFactura> tbFactura { get; set; }
        public virtual DbSet<tbFacturaDetalle> tbFacturaDetalle { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbPaquetes> tbPaquetes { get; set; }
        public virtual DbSet<tbPaquetesPorComidas> tbPaquetesPorComidas { get; set; }
        public virtual DbSet<tbPostres> tbPostres { get; set; }
        public virtual DbSet<tbPromociones> tbPromociones { get; set; }
        public virtual DbSet<tbPromocionesPorComidas> tbPromocionesPorComidas { get; set; }
        public virtual DbSet<tbPromocionesPorSusursales> tbPromocionesPorSusursales { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbSucursales> tbSucursales { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbAlimentos>(entity =>
            {
                entity.HasKey(e => e.Alim_Id)
                    .HasName("PK__tbAlimen__02198834A30E15BF");

                entity.ToTable("tbAlimentos", "Rest");

                entity.Property(e => e.Alim_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Alim_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Alim_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Alim_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Alim_Imagen).IsUnicode(false);

                entity.Property(e => e.Alim_Precio).HasColumnType("money");

                entity.HasOne(d => d.Alim_Usua_CreacionNavigation)
                    .WithMany(p => p.tbAlimentosAlim_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Alim_Usua_Creacion)
                    .HasConstraintName("Fk_tbAlimentos_Usua_Creacion");

                entity.HasOne(d => d.Alim_Usua_ModificaNavigation)
                    .WithMany(p => p.tbAlimentosAlim_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Alim_Usua_Modifica)
                    .HasConstraintName("Fk_tbAlimentos_Usua_Modifica");
            });

            modelBuilder.Entity<tbBebidas>(entity =>
            {
                entity.HasKey(e => e.Bebi_Id)
                    .HasName("PK__tbBebida__5E56F10B677E8E38");

                entity.ToTable("tbBebidas", "Rest");

                entity.Property(e => e.Bebi_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Bebi_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Bebi_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Bebi_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Bebi_Imagen).IsUnicode(false);

                entity.Property(e => e.Bebi_Precio).HasColumnType("money");

                entity.HasOne(d => d.Bebi_Usua_CreacionNavigation)
                    .WithMany(p => p.tbBebidasBebi_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Bebi_Usua_Creacion)
                    .HasConstraintName("Fk_tbBebidas_Usua_Creacion");

                entity.HasOne(d => d.Bebi_Usua_ModificaNavigation)
                    .WithMany(p => p.tbBebidasBebi_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Bebi_Usua_Modifica)
                    .HasConstraintName("Fk_tbBebidas_Usua_Modifica");
            });

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.Carg_Id)
                    .HasName("PK__tbCargos__B0D859FA73CEC67C");

                entity.ToTable("tbCargos", "Acce");

                entity.Property(e => e.Carg_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Carg_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Carg_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Carg_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Carg_Usua_CreacionNavigation)
                    .WithMany(p => p.tbCargosCarg_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Carg_Usua_Creacion)
                    .HasConstraintName("Fk_tbCargos_Usua_Creacion");

                entity.HasOne(d => d.Carg_Usua_ModificaNavigation)
                    .WithMany(p => p.tbCargosCarg_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Carg_Usua_Modifica)
                    .HasConstraintName("Fk_tbCargos_Usua_Modifica");
            });

            modelBuilder.Entity<tbClientes>(entity =>
            {
                entity.HasKey(e => e.Clie_Id)
                    .HasName("PK__tbClient__5BB955038746FC4F");

                entity.ToTable("tbClientes", "Gral");

                entity.Property(e => e.Clie_Apellido)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Clie_Correo)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Clie_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Clie_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Clie_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Clie_Identidad)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Clie_Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Clie_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Muni_Codigo)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.HasOne(d => d.Carg)
                    .WithMany(p => p.tbClientes)
                    .HasForeignKey(d => d.Carg_Id)
                    .HasConstraintName("Fk_tbClientes_Carg_Id");

                entity.HasOne(d => d.Clie_Usua_CreacionNavigation)
                    .WithMany(p => p.tbClientesClie_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Clie_Usua_Creacion)
                    .HasConstraintName("Fk_tbClientes_Usua_Creacion");

                entity.HasOne(d => d.Clie_Usua_ModificaNavigation)
                    .WithMany(p => p.tbClientesClie_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Clie_Usua_Modifica)
                    .HasConstraintName("Fk_tbClientes_Usua_Modifica");

                entity.HasOne(d => d.Esta)
                    .WithMany(p => p.tbClientes)
                    .HasForeignKey(d => d.Esta_Id)
                    .HasConstraintName("Fk_tbClientes_Esta_Id");

                entity.HasOne(d => d.Muni_CodigoNavigation)
                    .WithMany(p => p.tbClientes)
                    .HasForeignKey(d => d.Muni_Codigo)
                    .HasConstraintName("Fk_tbClientes_Muni_Codigo");
            });

            modelBuilder.Entity<tbCombosPersonales>(entity =>
            {
                entity.HasKey(e => e.Comb_Id)
                    .HasName("PK__tbCombos__D1035637FCA97E54");

                entity.ToTable("tbCombosPersonales", "Rest");

                entity.Property(e => e.Comb_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Comb_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Comb_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Comb_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Comb_Imagen).IsUnicode(false);

                entity.Property(e => e.Comb_Precio).HasColumnType("money");

                entity.HasOne(d => d.Alim)
                    .WithMany(p => p.tbCombosPersonales)
                    .HasForeignKey(d => d.Alim_Id)
                    .HasConstraintName("Fk_tbCombosPersonales_Alim_Id");

                entity.HasOne(d => d.Bebi)
                    .WithMany(p => p.tbCombosPersonales)
                    .HasForeignKey(d => d.Bebi_Id)
                    .HasConstraintName("Fk_tbCombosPersonales_Bebi_Id");

                entity.HasOne(d => d.Comb_Usua_CreacionNavigation)
                    .WithMany(p => p.tbCombosPersonalesComb_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Comb_Usua_Creacion)
                    .HasConstraintName("Fk_tbCombosPersonales_Usua_Creacion");

                entity.HasOne(d => d.Comb_Usua_ModificaNavigation)
                    .WithMany(p => p.tbCombosPersonalesComb_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Comb_Usua_Modifica)
                    .HasConstraintName("Fk_tbCombosPersonales_Usua_Modifica");

                entity.HasOne(d => d.Comp)
                    .WithMany(p => p.tbCombosPersonales)
                    .HasForeignKey(d => d.Comp_Id)
                    .HasConstraintName("Fk_tbCombosPersonales_Comp_Id");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.tbCombosPersonales)
                    .HasForeignKey(d => d.Post_id)
                    .HasConstraintName("Fk_tbCombosPersonales_Post_id");
            });

            modelBuilder.Entity<tbComplementos>(entity =>
            {
                entity.HasKey(e => e.Comp_Id)
                    .HasName("PK__tbComple__DC0BCC20831311EA");

                entity.ToTable("tbComplementos", "Rest");

                entity.Property(e => e.Comp_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Comp_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Comp_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Comp_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Comp_Imagen).IsUnicode(false);

                entity.Property(e => e.Comp_Precio).HasColumnType("money");

                entity.HasOne(d => d.Comp_Usua_CreacionNavigation)
                    .WithMany(p => p.tbComplementosComp_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Comp_Usua_Creacion)
                    .HasConstraintName("Fk_tbComplementos_Usua_Creacion");

                entity.HasOne(d => d.Comp_Usua_ModificaNavigation)
                    .WithMany(p => p.tbComplementosComp_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Comp_Usua_Modifica)
                    .HasConstraintName("Fk_tbComplementos_Usua_Modifica");
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.Dept_Codigo)
                    .HasName("PK__tbDepart__02786912D2D41EF0");

                entity.ToTable("tbDepartamentos", "Gral");

                entity.Property(e => e.Dept_Codigo)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Dept_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Dept_Usua_CreacionNavigation)
                    .WithMany(p => p.tbDepartamentosDept_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Dept_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbDepartamentos_Usua_Creacion");

                entity.HasOne(d => d.Dept_Usua_ModificaNavigation)
                    .WithMany(p => p.tbDepartamentosDept_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Dept_Usua_Modifica)
                    .HasConstraintName("Fk_tbDepartamentos_Usua_Modifica");
            });

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.Empl_Id)
                    .HasName("PK__tbEmplea__2EB12E86B30994F0");

                entity.ToTable("tbEmpleados", "Gral");

                entity.Property(e => e.Empl_Apellido)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Empl_Correo)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Empl_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Empl_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Empl_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Empl_Identidad)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Empl_Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Empl_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.Muni_Codigo)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.HasOne(d => d.Carg)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Carg_Id)
                    .HasConstraintName("Fk_tbEmpleados_Carg_Id");

                entity.HasOne(d => d.Empl_Usua_CreacionNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Empl_Usua_Creacion)
                    .HasConstraintName("Fk_tbEmpleados_Usua_Creacion");

                entity.HasOne(d => d.Empl_Usua_ModificaNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Empl_Usua_Modifica)
                    .HasConstraintName("Fk_tbEmpleados_Usua_Modifica");

                entity.HasOne(d => d.Esta)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Esta_Id)
                    .HasConstraintName("Fk_tbEmpleados_Esta_Id");

                entity.HasOne(d => d.Muni_CodigoNavigation)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Muni_Codigo)
                    .HasConstraintName("Fk_tbEmpleados_Muni_Codigo");
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.Esta_Id)
                    .HasName("PK__tbEstado__D52AE7B85D0FEF35");

                entity.ToTable("tbEstadosCiviles", "Gral");

                entity.Property(e => e.Esta_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Esta_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Esta_Usua_CreacionNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsta_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Esta_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbEstadosCiviles_Usua_Creacion");

                entity.HasOne(d => d.Esta_Usua_ModificaNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsta_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Esta_Usua_Modifica)
                    .HasConstraintName("Fk_tbEstadosCiviles_Usua_Modifica");
            });

            modelBuilder.Entity<tbFactura>(entity =>
            {
                entity.HasKey(e => e.Fact_Id)
                    .HasName("PK__tbFactur__8327E027845356CB");

                entity.ToTable("tbFactura", "Rest");

                entity.Property(e => e.Fact_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Fact_Fecha).HasColumnType("date");

                entity.Property(e => e.Fact_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Fact_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Fact_Total).HasColumnType("money");

                entity.HasOne(d => d.Empl)
                    .WithMany(p => p.tbFactura)
                    .HasForeignKey(d => d.Empl_Id)
                    .HasConstraintName("Fk_tbFactura_Empl_Id");

                entity.HasOne(d => d.Fact_Usua_CreacionNavigation)
                    .WithMany(p => p.tbFacturaFact_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Fact_Usua_Creacion)
                    .HasConstraintName("Fk_tbFactura_Usua_Creacion");

                entity.HasOne(d => d.Fact_Usua_ModificaNavigation)
                    .WithMany(p => p.tbFacturaFact_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Fact_Usua_Modifica)
                    .HasConstraintName("Fk_tbFactura_Usua_Modifica");

                entity.HasOne(d => d.Sucu)
                    .WithMany(p => p.tbFactura)
                    .HasForeignKey(d => d.Sucu_Id)
                    .HasConstraintName("Fk_tbFactura_Sucu_Id");
            });

            modelBuilder.Entity<tbFacturaDetalle>(entity =>
            {
                entity.HasKey(e => e.FaDe_Id)
                    .HasName("PK__tbFactur__99C2F8F9B10536D9");

                entity.ToTable("tbFacturaDetalle", "Rest");

                entity.Property(e => e.FaDe_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.FaDe_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.FaDe_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.FaDe_Subtotal).HasColumnType("money");

                entity.HasOne(d => d.Alim)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Alim_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Alim_Id");

                entity.HasOne(d => d.Bebi)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Bebi_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Bebi_Id");

                entity.HasOne(d => d.Comb)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Comb_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Comb_Id");

                entity.HasOne(d => d.Comp)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Comp_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Comp_Id");

                entity.HasOne(d => d.FaDe_Usua_CreacionNavigation)
                    .WithMany(p => p.tbFacturaDetalleFaDe_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.FaDe_Usua_Creacion)
                    .HasConstraintName("Fk_tbFacturaDetalle_Usua_Creacion");

                entity.HasOne(d => d.FaDe_Usua_ModificaNavigation)
                    .WithMany(p => p.tbFacturaDetalleFaDe_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.FaDe_Usua_Modifica)
                    .HasConstraintName("Fk_tbFacturaDetalle_Usua_Modifica");

                entity.HasOne(d => d.Fact)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Fact_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Fact_Id");

                entity.HasOne(d => d.Paqe)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Paqe_Id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Paqe_Id");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.tbFacturaDetalle)
                    .HasForeignKey(d => d.Post_id)
                    .HasConstraintName("Fk_tbFacturaDetalle_Post_id");
            });

            modelBuilder.Entity<tbMunicipios>(entity =>
            {
                entity.HasKey(e => e.Muni_Codigo)
                    .HasName("PK__tbMunici__289AC128566A8D5A");

                entity.ToTable("tbMunicipios", "Gral");

                entity.Property(e => e.Muni_Codigo)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Dept_Codigo)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Muni_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Muni_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Muni_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Dept_CodigoNavigation)
                    .WithMany(p => p.tbMunicipios)
                    .HasForeignKey(d => d.Dept_Codigo)
                    .HasConstraintName("Fk_tbMunicipios_Dept_Codigo");

                entity.HasOne(d => d.Muni_Usua_CreacionNavigation)
                    .WithMany(p => p.tbMunicipiosMuni_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Muni_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("Fk_tbMunicipios_Usua_Creacion");

                entity.HasOne(d => d.Muni_Usua_ModificaNavigation)
                    .WithMany(p => p.tbMunicipiosMuni_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Muni_Usua_Modifica)
                    .HasConstraintName("Fk_tbMunicipios_Usua_Modifica");
            });

            modelBuilder.Entity<tbPantallas>(entity =>
            {
                entity.HasKey(e => e.Pant_Id)
                    .HasName("PK__tbPantal__CF98C932ED2E42F1");

                entity.ToTable("tbPantallas", "Acce");

                entity.Property(e => e.Pant_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pant_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Pant_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Pant_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Pant_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPant_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Pant_Usua_Creacion)
                    .HasConstraintName("Fk_tbPantallas_Usua_Creacion");

                entity.HasOne(d => d.Pant_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPantallasPant_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Pant_Usua_Modifica)
                    .HasConstraintName("Fk_tbPantallas_Usua_Modifica");
            });

            modelBuilder.Entity<tbPantallasPorRoles>(entity =>
            {
                entity.HasKey(e => e.Paro_Id)
                    .HasName("PK__tbPantal__53819DE91D6C7C01");

                entity.ToTable("tbPantallasPorRoles", "Acce");

                entity.Property(e => e.Paro_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Paro_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Paro_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Pant)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Pant_Id)
                    .HasConstraintName("Fk_tbPantallasPorRoles_Pant_Id");

                entity.HasOne(d => d.Paro_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPorRolesParo_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Paro_Usua_Creacion)
                    .HasConstraintName("Fk_tbPantallasPorRoles_Usua_Creacion");

                entity.HasOne(d => d.Paro_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPantallasPorRolesParo_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Paro_Usua_Modifica)
                    .HasConstraintName("Fk_tbPantallasPorRoles_Usua_Modifica");

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Rol_Id)
                    .HasConstraintName("Fk_tbPantallasPorRoles_Roles_Id");
            });

            modelBuilder.Entity<tbPaquetes>(entity =>
            {
                entity.HasKey(e => e.Paqe_Id)
                    .HasName("PK__tbPaquet__9F66E04D7E7C1499");

                entity.ToTable("tbPaquetes", "Rest");

                entity.Property(e => e.Paqe_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Paqe_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Paqe_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Paqe_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Paqe_Imagen).IsUnicode(false);

                entity.Property(e => e.Paqe_Precio).HasColumnType("money");

                entity.HasOne(d => d.Paqe_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPaquetesPaqe_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Paqe_Usua_Creacion)
                    .HasConstraintName("Fk_tbPaquetes_Usua_Creacion");

                entity.HasOne(d => d.Paqe_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPaquetesPaqe_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Paqe_Usua_Modifica)
                    .HasConstraintName("Fk_tbPaquetes_Usua_Modifica");
            });

            modelBuilder.Entity<tbPaquetesPorComidas>(entity =>
            {
                entity.HasKey(e => e.PaCo_Id)
                    .HasName("PK__tbPaquet__E71C6FCB2F9ED8A5");

                entity.ToTable("tbPaquetesPorComidas", "Rest");

                entity.Property(e => e.PaCo_Id).ValueGeneratedNever();

                entity.Property(e => e.PaCo_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.PaCo_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.PaCo_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Alim)
                    .WithMany(p => p.tbPaquetesPorComidas)
                    .HasForeignKey(d => d.Alim_Id)
                    .HasConstraintName("Fk_tbPaquetesPorComidas_Alim_Id");

                entity.HasOne(d => d.Bebi)
                    .WithMany(p => p.tbPaquetesPorComidas)
                    .HasForeignKey(d => d.Bebi_Id)
                    .HasConstraintName("Fk_tbPaquetesPorComidas_Bebi_Id");

                entity.HasOne(d => d.Comp)
                    .WithMany(p => p.tbPaquetesPorComidas)
                    .HasForeignKey(d => d.Comp_Id)
                    .HasConstraintName("Fk_tbPaquetesPorComidas_Comp_Id");

                entity.HasOne(d => d.PaCo_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPaquetesPorComidasPaCo_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.PaCo_Usua_Creacion)
                    .HasConstraintName("Fk_tbPaquetesPorComidasas_Usua_Creacion");

                entity.HasOne(d => d.PaCo_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPaquetesPorComidasPaCo_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.PaCo_Usua_Modifica)
                    .HasConstraintName("Fk_tbPaquetesPorComidasas_Usua_Modifica");

                entity.HasOne(d => d.Paqe)
                    .WithMany(p => p.tbPaquetesPorComidas)
                    .HasForeignKey(d => d.Paqe_Id)
                    .HasConstraintName("Fk_tbPaquetesPorComidas_Paqe_Id");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.tbPaquetesPorComidas)
                    .HasForeignKey(d => d.Post_id)
                    .HasConstraintName("Fk_tbPaquetesPorComidas_Post_id");
            });

            modelBuilder.Entity<tbPostres>(entity =>
            {
                entity.HasKey(e => e.Post_id)
                    .HasName("PK__tbPostre__587ADB657476D6CC");

                entity.ToTable("tbPostres", "Rest");

                entity.Property(e => e.Post_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Post_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Post_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Post_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Post_Imagen).IsUnicode(false);

                entity.Property(e => e.Post_Precio).HasColumnType("money");

                entity.HasOne(d => d.Post_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPostresPost_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Post_Usua_Creacion)
                    .HasConstraintName("Fk_tbPostres_Usua_Creacion");

                entity.HasOne(d => d.Post_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPostresPost_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Post_Usua_Modifica)
                    .HasConstraintName("Fk_tbPostres_Usua_Modifica");
            });

            modelBuilder.Entity<tbPromociones>(entity =>
            {
                entity.HasKey(e => e.Prom_Id)
                    .HasName("PK__tbPromoc__3FD063B76403A288");

                entity.ToTable("tbPromociones", "Rest");

                entity.Property(e => e.Prom_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Prom_Dia)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Prom_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Prom_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Prom_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Prom_Imagen).IsUnicode(false);

                entity.Property(e => e.Prom_Precio).HasColumnType("money");

                entity.HasOne(d => d.Prom_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPromocionesProm_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Prom_Usua_Creacion)
                    .HasConstraintName("Fk_tbPromociones_Usua_Creacion");

                entity.HasOne(d => d.Prom_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPromocionesProm_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Prom_Usua_Modifica)
                    .HasConstraintName("Fk_tbPromociones_Usua_Modifica");
            });

            modelBuilder.Entity<tbPromocionesPorComidas>(entity =>
            {
                entity.HasKey(e => e.PrSe_Id)
                    .HasName("PK__tbPromoc__992DDE1B1213C096");

                entity.ToTable("tbPromocionesPorComidas", "Rest");

                entity.Property(e => e.PrSe_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.PrSe_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.PrSe_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Alim)
                    .WithMany(p => p.tbPromocionesPorComidas)
                    .HasForeignKey(d => d.Alim_Id)
                    .HasConstraintName("Fk_tbPromocionesPorComidas_Alim_Id");

                entity.HasOne(d => d.Bebi)
                    .WithMany(p => p.tbPromocionesPorComidas)
                    .HasForeignKey(d => d.Bebi_Id)
                    .HasConstraintName("Fk_tbPromocionesPorComidas_Bebi_Id");

                entity.HasOne(d => d.Comp)
                    .WithMany(p => p.tbPromocionesPorComidas)
                    .HasForeignKey(d => d.Comp_Id)
                    .HasConstraintName("Fk_tbPromocionesPorComidas_Comp_Id");

                entity.HasOne(d => d.Post)
                    .WithMany(p => p.tbPromocionesPorComidas)
                    .HasForeignKey(d => d.Post_id)
                    .HasConstraintName("Fk_tbPromocionesPorComidas_Post_id");

                entity.HasOne(d => d.PrSe_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPromocionesPorComidasPrSe_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.PrSe_Usua_Creacion)
                    .HasConstraintName("Fk_tbPromocionesPorComidass_Usua_Creacion");

                entity.HasOne(d => d.PrSe_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPromocionesPorComidasPrSe_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.PrSe_Usua_Modifica)
                    .HasConstraintName("Fk_tbPromocionesPorComidass_Usua_Modifica");

                entity.HasOne(d => d.Prom)
                    .WithMany(p => p.tbPromocionesPorComidas)
                    .HasForeignKey(d => d.Prom_Id)
                    .HasConstraintName("Fk_tbPromocionesPorComidas_Prom_Id");
            });

            modelBuilder.Entity<tbPromocionesPorSusursales>(entity =>
            {
                entity.HasKey(e => e.PPSu_Id)
                    .HasName("PK__tbPromoc__D29C1F0E79CF3AC9");

                entity.ToTable("tbPromocionesPorSusursales", "Rest");

                entity.Property(e => e.PPSu_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.PPSu_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.PPSu_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Prom)
                    .WithMany(p => p.tbPromocionesPorSusursales)
                    .HasForeignKey(d => d.Prom_Id)
                    .HasConstraintName("Fk_tbPromocionesPorSucursales_Prom_Id");

                entity.HasOne(d => d.Sucu)
                    .WithMany(p => p.tbPromocionesPorSusursales)
                    .HasForeignKey(d => d.Sucu_Id)
                    .HasConstraintName("Fk_tbPromocionesPorSucursales_Sucu_Id");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Rol_Id)
                    .HasName("PK__tbRoles__795EBD490A751D75");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.Rol_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Rol_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Rol_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Rol_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Rol_Usua_CreacionNavigation)
                    .WithMany(p => p.tbRolesRol_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Rol_Usua_Creacion)
                    .HasConstraintName("Fk_tbRoles_Usua_Creacion");

                entity.HasOne(d => d.Rol_Usua_ModificaNavigation)
                    .WithMany(p => p.tbRolesRol_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Rol_Usua_Modifica)
                    .HasConstraintName("Fk_tbRoles_Usua_Modifica");
            });

            modelBuilder.Entity<tbSucursales>(entity =>
            {
                entity.HasKey(e => e.Sucu_Id)
                    .HasName("PK__tbSucurs__23271C400962BB25");

                entity.ToTable("tbSucursales", "Rest");

                entity.Property(e => e.Muni_Codigo)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Sucu_Descripcion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Sucu_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Sucu_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Sucu_Fecha_Modifica).HasColumnType("date");

                entity.HasOne(d => d.Empl)
                    .WithMany(p => p.tbSucursales)
                    .HasForeignKey(d => d.Empl_Id)
                    .HasConstraintName("Fk_tbSucursales_Empl_Id");

                entity.HasOne(d => d.Muni_CodigoNavigation)
                    .WithMany(p => p.tbSucursales)
                    .HasForeignKey(d => d.Muni_Codigo)
                    .HasConstraintName("Fk_tbSucursales_Muni_Codigo");

                entity.HasOne(d => d.Sucu_Usua_CreacionNavigation)
                    .WithMany(p => p.tbSucursalesSucu_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Sucu_Usua_Creacion)
                    .HasConstraintName("Fk_tbSucursales_Usua_Creacion");

                entity.HasOne(d => d.Sucu_Usua_ModificaNavigation)
                    .WithMany(p => p.tbSucursalesSucu_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Sucu_Usua_Modifica)
                    .HasConstraintName("Fk_tbSucursales_Usua_Modifica");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EE6D15AEBB");

                entity.ToTable("tbUsuarios", "Acce");

                entity.Property(e => e.Usua_Activo).HasDefaultValueSql("((1))");

                entity.Property(e => e.Usua_Contra).IsUnicode(false);

                entity.Property(e => e.Usua_Fecha_Creacion).HasColumnType("date");

                entity.Property(e => e.Usua_Fecha_Modifica).HasColumnType("date");

                entity.Property(e => e.Usua_Usuario)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Empl)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Empl_Id)
                    .HasConstraintName("Fk_tbUsuarios_Empl_Id");

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Rol_Id)
                    .HasConstraintName("Fk_tbUsuarios_Rol_Id");

                entity.HasOne(d => d.Usua_Usua_CreacionNavigation)
                    .WithMany(p => p.InverseUsua_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Usua_Usua_Creacion)
                    .HasConstraintName("Fk_tbUsuarios_Usua_Usua_Creacion");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}